// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk1_JIC5ZGTY_LqTU4R7xemD9-v0ZhvPo',
    appId: '1:732563246836:web:73189f72648dbe6bba18a1',
    messagingSenderId: '732563246836',
    projectId: 'smarak-9ffc9',
    authDomain: 'smarak-9ffc9.firebaseapp.com',
    storageBucket: 'smarak-9ffc9.firebasestorage.app',
    measurementId: 'G-446FXCNJD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn-p7vDO_S3npempxrIYefM9Nh9KlH7L4',
    appId: '1:732563246836:android:39d91c953de8a6b1ba18a1',
    messagingSenderId: '732563246836',
    projectId: 'smarak-9ffc9',
    storageBucket: 'smarak-9ffc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoCA29LdR1GFW6F2h5qDdSSQemgXzyfCY',
    appId: '1:732563246836:ios:96d47ecc6a06b83eba18a1',
    messagingSenderId: '732563246836',
    projectId: 'smarak-9ffc9',
    storageBucket: 'smarak-9ffc9.firebasestorage.app',
    iosBundleId: 'com.example.smarak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoCA29LdR1GFW6F2h5qDdSSQemgXzyfCY',
    appId: '1:732563246836:ios:96d47ecc6a06b83eba18a1',
    messagingSenderId: '732563246836',
    projectId: 'smarak-9ffc9',
    storageBucket: 'smarak-9ffc9.firebasestorage.app',
    iosBundleId: 'com.example.smarak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk1_JIC5ZGTY_LqTU4R7xemD9-v0ZhvPo',
    appId: '1:732563246836:web:4ed7184387350e5aba18a1',
    messagingSenderId: '732563246836',
    projectId: 'smarak-9ffc9',
    authDomain: 'smarak-9ffc9.firebaseapp.com',
    storageBucket: 'smarak-9ffc9.firebasestorage.app',
    measurementId: 'G-SK5CVJZSV1',
  );

}